<?php

namespace FastFrame\Composer\Packages\Packages;

/**
 * This interface will be auto-generated by the Plugin
 *
 * @package FastFrame\Composer\Packages\Packages
 */
interface Packages
{
	public const ROOT_PATH = '';
	public const PACKAGES  = array();
	public const TYPES     = array();
}