name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0]
        experimental: [false]
        include:
          - php: 8.0
            analysis: true
          - php: 8.1
            experimental: true
    steps:
    - uses: actions/checkout@v1
    - name: PHP ${{ matrix.php }}
      if: matrix.analysis
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug
    - name: Install dependencies with Composer
      uses: ramsey/composer-install@v1
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Coding standards
      if: matrix.analysis
      run: composer sniff
    - name: Tests
      run: composer test
